apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: thorsten.hans@thinktecture.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-tls
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx
